### ISSUE TITLE
怎么得到返回的结果？

### ISSUE THREAD

**Issue by jarlemon** [luckcoding/koa-middle-validator#1]
为什么调用了getValidationResult方法返回了这个结果了
![微信图片_20190621221204](https://user-images.githubusercontent.com/30827091/59928706-ee324d00-9471-11e9-93c4-2442235717b9.png)

**Comment by luckcoding** [comment]
> 为什么调用了getValidationResult方法返回了这个结果了
> ![微信图片_20190621221204](https://user-images.githubusercontent.com/30827091/59928706-ee324d00-9471-11e9-93c4-2442235717b9.png)

```
getValidationResult.then(errors => {
  // result
  console.log(errors.array());
})
```
[demo](https://github.com/luckcoding/koa-middle-validator/blob/master/test/getValidationErrorsTest.js)
