### ISSUE TITLE
Update validator dependency

### ISSUE THREAD

**Issue by yentsun** [luckcoding/koa-middle-validator#2]
Currently `validator` package is at version `11.1.0`, but `koa-middle-validator` has `validator` dependency @`^6.2.0`.

This is probably the reason I get errors for validators like `isISO31661Alpha3`.

```
Error: Cannot read property 'apply' of undefined
    at validateSchema (/mnt/storage/Projects/SimpleCrew/backend-api/node_modules/koa-middle-validator/lib/koa_validator.js:451:29)
```

**Comment by luckcoding** [comment]
Please update to v1.2.0

**Comment by luckcoding** [comment]
> Currently `validator` package is at version `11.1.0`, but `koa-middle-validator` has `validator` dependency @`^6.2.0`.
> 
> This is probably the reason I get errors for validators like `isISO31661Alpha3`.
> 
> ```
> Error: Cannot read property 'apply' of undefined
>     at validateSchema (/mnt/storage/Projects/SimpleCrew/backend-api/node_modules/koa-middle-validator/lib/koa_validator.js:451:29)
> ```

Please update to v1.2.0
