### ISSUE TITLE
两个参数必须填一个填检验怎么写

### ISSUE THREAD

**Issue by jinweizhiyuan** [luckcoding/koa-middle-validator#3]
看了一下文档，没有发现两参数中必须填写一个参数的检验写法，现在检验器能满足这种需求吗

**Comment by luckcoding** [comment]
> 看了一下文档，没有发现两参数中必须填写一个参数的检验写法，现在检验器能满足这种需求吗

不支持这种校验方式。可试试我新写的这个库[koa-controller](https://github.com/luckcoding/koa-controller)，采用joi验证，支持你所说的这种场景。
